### ISSUE TITLE
Add routes to get transactions by lenderID and borrowerID

### ISSUE THREAD

**Issue by mxkay** [mxkay/forgotten-backend#12]
We will need to add routes to get transactions by the lenderID and borrowerID. These routes will be used when on the Profile page and viewing a filtered feed of transactions.

**Comment by Dychotomy** [comment]
I've been thinking about this, do we need additional routes? I'm assuming that the lender/borrower ids will be "hidden" entries. Would it make more sense to have the lenderName or BorrowerName make a get call on users and check for matches against name/handle and if true fill in the keys with the appropriate ids?

**Comment by mxkay** [comment]
Thinking about the use case of these calls... we will only use these calls when we are on the profile page and we want to filter for transactions involving the user (the user is a lender or a borrower). We will always know the user ID, because they will have to sign in before accessing other parts of the app. It makes sense to use the ID here, because we don't want two users with the same name to show up in the same filter

**Comment by mxkay** [comment]
As we discussed in the meeting, this can actually be a single API call that gets all transactions where the req.params.id is equal to either the borrowerID or the lenderID. Then we can filter the results in the front-end
