### ISSUE TITLE
React architecture and wireframes

### ISSUE THREAD

**Issue by wt08** [mxkay/forgotten-backend#3]
React architecture and wireframes needed to finish project wksht.

**Comment by Dychotomy** [comment]
Uploaded wire-frames and react architecture.

**Comment by mxkay** [comment]
Built wireframes and created react component diagrams to help us with design

![wireframe](https://user-images.githubusercontent.com/63630918/87828777-a8e67780-c84b-11ea-86d0-434d1145e0d6.png)
![component_diagram](https://user-images.githubusercontent.com/63630918/87828822-c3b8ec00-c84b-11ea-8655-cea1bcfab76e.png)
